# This is a basic workflow to help you get started with Actions
name: Update fork

env:
  IS_DESIHIGH: 'True'

# Controls when the action will run. 
on:
  schedule:
    # Every Monday at 1PM UTC (9AM EST)
    - cron: "30 18 * * 4" 

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set upstream
        run: git remote add upstream https://github.com/michaelJwilson/desihigh.git
      - name: Set email
        run: git config --local user.email "action@github.com"
      - name: Set username
        run: git config --local user.name "GitHub Action"
      - name: Fetch upstream
        run: git fetch upstream
      - name: Merge upstream
        run: git merge upstream/main --allow-unrelated-histories
      - name: Push changes 
        run: git push 
